### ISSUE TITLE
api のエンドポイント(パス)はなるべく短く簡潔である方がいい

### ISSUE THREAD

**Issue by earlgray283** [kajikaji0725/ToDo-App#1]
http リクエストには必ずメソッドがついており、それでクライアントは何をしたいのかを見分けることができるから api のエンドポイントで get/set をつける意味はあんまりない。
だから、シンプルに
```
/homework
```
にしてそこへのリクエストを get と post で見分けるようにすればいいんじゃないかな？あと、id の指定で全部返すか1つ返すかの処理も `[GET] /homework` のハンドラの中でやれば良さそう。

**Comment by kajikaji0725** [comment]
なるほど。
良いことを聞きました
