### ISSUE TITLE
ハンドリング中に死ぬな

### ISSUE THREAD

**Issue by earlgray283** [kajikaji0725/ToDo-App#2]
```go
func setHomework(w http.ResponseWriter, r *http.Request) {
	resp, _ := ioutil.ReadAll(r.Body)
	var person Homework
	if err := json.Unmarshal(resp, &person); err != nil {
		log.Fatal(err)
	}

	persons = append(persons, &person)
	json.NewEncoder(w).Encode(person)
}
```

これだと、json 形式を誤ったリクエスト1つだけのせいでサーバー自体が死ぬことになる。それは流石にやばいので、`http.Error(rw, "json parsing error", 400)` でレスポンスを返して早期 return をすべき。

**Comment by kajikaji0725** [comment]
サーバーの可用性の点では非常に大切ですね。
良いことを知った

**Comment by earlgray283** [comment]
`http.Error()` の内部では早期 return はしてくれないから自分で return 文を追加してあげないといけない

**Comment by earlgray283** [comment]
/getSingleFetchHomework/{key} は /homework/{key} でいいと思う

**Comment by kajikaji0725** [comment]
return書くの忘れてました。
pathがめちゃくちゃ短く....　感動
